export const api = {
  popularMovies: "/discover/movie",
  trendingMovies: "/trending/movie/week",
  upcomingMovies: `/movie/upcoming`,
  multiSearch: "/trending/movie/week",
  movieGenres: "/genre/movie/list",
  movieList: (id: string) => `/list/${id}`,
  movie: (id: string) => `/movie/${id}`,
  credits: (id: string) => `/movie/${id}/credits`,
  reviews: (id: string) => `/movie/${id}/reviews`,
  keywords: (id: string) => `/movie/${id}/keywords`,
  person: (id: string) => `/person/${id}`,
  personExternals: (id: string) => `/person/${id}/external_ids`,
  personCombinedCredits: (id: string) => `/person/${id}/combined_credits`,
  itemsByKeyword: "/discover/movie",
  keyword: (id: string) => `/keyword/${id}`,
  similarMovies: (id: string) => `/movie/${id}/similar`,
  recommendedMovies: (id: string) => `/movie/${id}/recommendations`,
  movieImages: (id: string) => `/movie/${id}/images`,
  movieVideos: (id: string) => `/movie/${id}/videos`,
  personImages: (id: string) => `/person/${id}/images`,
  collection: (id: string) => `/collection/${id}`,
  searchMovie: "/search/movie",
  searchPerson: "/search/person",
};